spring:
  application:
    name: zuul-router

server:
  port: 8080
  servletPath: /

zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  addProxyHeaders: true

  routes:
    books:
      path: /books/**
      serviceId: book
      stripPrefix: false

eureka:
  server:
    host: localhost
    port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.server.host}:${eureka.server.port}/eureka/
    healthcheck:
      enabled: true
    instance:
      statusPageUrlPath: ${server.servletPath}info
      healthCheckUrlPath: ${server.servletPath}health
