spring:
  application:
    name: book

server:
  port: 8091
  servletPath: /

eureka:
  server:
    host: localhost
    port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.server.host}:${eureka.server.port}/eureka/
    healthcheck:
      enabled: true
    instance:
      statusPageUrlPath: ${server.servletPath}info
      healthCheckUrlPath: ${server.servletPath}health
